name: update brave-bin templates

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run update.sh script
        run: (cd srcpkgs/brave-nightly-bin && ./update.sh)
      - name: Push updated template
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git add srcpkgs/brave-nightly-bin
          git commit -m "brave-nightly-bin: update $(date --iso-8601=seconds)"
          git push
  update-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run update.sh script
        run: (cd srcpkgs/brave-dev-bin && ./update.sh)
      - name: Push updated template
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git add srcpkgs/brave-nightly-bin
          git commit -m "brave-nightly-bin: update $(date --iso-8601=seconds)" || exit 0
          git push
