name: update package templates

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run update scripts and push
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          echo "update: brave-nightly-bin"
          (cd srcpkgs/brave-nightly-bin && ./update.sh)
          git add srcpkgs/brave-nightly-bin
          git commit -m "brave-nightly-bin: update $(date --iso-8601=seconds)" || echo "Nothing to commit"

          echo "update: brave-dev-bin"
          (cd srcpkgs/brave-dev-bin && ./update.sh)
          git add srcpkgs/brave-dev-bin
          git commit -m "brave-dev-bin: update $(date --iso-8601=seconds)" || echo "Nothing to commit"

          echo "update: google-chrome-dev-bin"
          (cd srcpkgs/google-chrome-dev-bin && ./update.sh)
          git add srcpkgs/google-chrome-dev-bin
          git commit -m "google-chrome-dev-bin: update $(date --iso-8601=seconds)" || echo "Nothing to commit"

          git push
